const test=require('node:test');const assert=require('node:assert/strict');const path=require('path');const request=require('supertest');const app=require('../src/server');
const sample=n=>path.join(__dirname,'../samples',n);
test('health, seeded projects, and downloadable samples are available',async()=>{const h=await request(app).get('/api/health').expect(200);assert.equal(h.body.mode,'deterministic-local');assert.ok(h.body.records>=10);const p=await request(app).get('/api/projects').expect(200);assert.ok(p.body.length>=10);const sampleFile=await request(app).get('/samples/sample-proposal.hwpx').expect(200);assert.ok(Number(sampleFile.headers['content-length'])>500);});
test('multi-file analysis extracts fields and marks missing evidence',async()=>{const res=await request(app).post('/api/analyze').attach('documents',sample('sample-proposal.docx')).attach('documents',sample('sample-proposal.xlsx')).attach('documents',sample('sample-proposal.hwpx')).expect(200);assert.equal(res.body.sourceFiles.length,3);assert.match(res.body.fields.projectName.value,/엣지 AI/);assert.match(res.body.fields.pi.value,/김미래/);assert.ok(res.body.fields.projectName.evidence);});
test('every supported upload format extracts proposal data',async()=>{for(const name of ['sample-proposal.pdf','sample-proposal.docx','sample-proposal.xlsx','sample-proposal.hwpx']){const res=await request(app).post('/api/analyze').attach('documents',sample(name)).expect(200);assert.equal(res.body.sourceFiles[0].extracted,true,name);assert.match(res.body.fields.projectName.value,/엣지 AI/,name);assert.match(res.body.fields.deliverables.value,/위험예측 소프트웨어/,name);}});
test('Korean PDF filename is preserved in evidence',async()=>{const res=await request(app).post('/api/analyze').attach('documents',require('fs').readFileSync(sample('sample-proposal.pdf')),{filename:'지원과제_계획서.pdf',contentType:'application/pdf'}).expect(200);assert.equal(res.body.sourceFiles[0].name,'지원과제_계획서.pdf');assert.match(res.body.fields.projectName.evidence,/지원과제_계획서\.pdf/);});
test('section headings can capture multi-line purpose and goal evidence',()=>{const out=require('../src/analyzer').analyzeText('연구기간\n2026.01~2029.12\n연구목표\n스마트폰 내부데이터 접근 보안 기술 개발을 달성한다.');assert.match(out.fields.period.value,/2026/);assert.match(out.fields.purpose.value,/스마트폰/);});
test('categorized upload preserves document roles',async()=>{const res=await request(app).post('/api/analyze').field('documentCategories',JSON.stringify(['사업계획서'])).attach('documents',sample('sample-proposal.pdf')).expect(200);assert.equal(res.body.sourceFiles[0].category,'사업계획서');assert.match(res.body.fields.projectName.evidence,/사업계획서/);});
test('legacy file fails gracefully',async()=>{const res=await request(app).post('/api/analyze').attach('documents',Buffer.from('legacy binary'),{filename:'legacy.hwp'}).expect(200);assert.equal(res.body.fields.projectName.value,'확인 필요');assert.ok(res.body.warnings.length);});
test('search compares eight dimensions with seeded and manual records',async()=>{const res=await request(app).post('/api/search').send({query:'엣지 AI 도시 침수 위험예측',proposal:{objective:'도시 침수 위험 조기예측',problem:'국지성 호우',technology:'엣지 AI IoT',method:'센서 융합',target:'지자체',application:'재난안전',deliverable:'예측 플랫폼',differentiation:'현장 추론'},manualInput:JSON.stringify([{id:'M-1',name:'침수 예측',objective:'도시 침수 위험 조기예측',technology:'엣지 AI IoT'}])}).expect(200);assert.ok(res.body.candidates.length);assert.equal(Object.keys(res.body.candidates[0].dimensions).length,8);assert.ok(res.body.candidates.some(x=>x.id==='M-1'));});
test('external credentials are ephemeral and validated',async()=>{const bad=await request(app).post('/api/external/research').send({url:'bad',id:'u',password:'secret',query:'q'}).expect(400);assert.ok(bad.body.error);const ok=await request(app).post('/api/external/research').send({url:'https://example.go.kr',id:'u',password:'secret',query:'q'}).expect(200);assert.equal(ok.body.persisted,false);assert.equal(JSON.stringify(ok.body).includes('secret'),false);});
test('editable reports download in DOCX, PDF, HTML',async()=>{const binary=processBinary();const review={fields:{projectName:{value:'테스트 과제',evidence:'샘플'}},eligibility:[{item:'자격',status:'적합',note:'확인'}],duplicateReviews:[{name:'기존과제',similarity:20,status:'적합',note:'차별'}],conclusion:'중복 아님',reviewer:{name:'홍길동',department:'평가팀'}};const d=await request(app).post('/api/report/docx').buffer(true).parse(binary).send(review).expect(200);assert.match(d.headers['content-type'],/officedocument/);assert.ok(d.body.length>1000);const p=await request(app).post('/api/report/pdf').buffer(true).parse(binary).send(review).expect(200);assert.equal(p.body.subarray(0,4).toString(),'%PDF');const h=await request(app).post('/api/report/html').send(review).expect(200);assert.match(h.text,/테스트 과제/);});
function processBinary(){return(res,cb)=>{res.setEncoding('binary');let data='';res.on('data',chunk=>data+=chunk);res.on('end',()=>cb(null,Buffer.from(data,'binary')));};}
