const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType } = require('docx');
const PDFDocument = require('pdfkit');
const fs = require('fs');

const PDF_FONT_CANDIDATES=[process.env.PDF_FONT_PATH,'/usr/share/fonts/opentype/unifont/unifont_jp.otf','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf','/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'].filter(Boolean);
const PDF_FONT=PDF_FONT_CANDIDATES.find(fs.existsSync);

const LABELS={projectName:'과제명',institution:'주관기관',pi:'연구책임자',period:'연구기간',purpose:'연구목적',contents:'연구내용',coreTechnology:'핵심기술',keywords:'키워드',finalGoal:'최종목표',deliverables:'성과물'};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function model(r={}) { return {fields:r.fields||{},eligibility:r.eligibility||[],candidates:r.candidates||[],duplicateReviews:r.duplicateReviews||[],conclusion:r.conclusion||'',reviewer:r.reviewer||{},completedAt:r.completedAt||new Date().toISOString()}; }
function htmlReport(review) {
  const r=model(review);
  return `<!doctype html><html lang="ko"><meta charset="utf-8"><title>ICT R&D 사전검토 보고서</title><style>body{font-family:Arial,'Malgun Gothic',sans-serif;margin:40px;color:#17233c}h1{border-bottom:3px solid #174b96;padding-bottom:12px}h2{color:#174b96;margin-top:28px}table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border:1px solid #aebbd0;padding:9px;text-align:left;vertical-align:top}th{background:#eaf1fb}.muted{color:#667085;font-size:12px}@media print{body{margin:14mm}}</style><h1>ICT R&D 선정평가 사전검토 보고서</h1><p class="muted">생성일시 ${esc(r.completedAt)} · 본 결과는 평가위원 판단을 지원하는 참고자료입니다.</p><h2>1. 신청과제</h2><table>${Object.entries(LABELS).map(([k,l])=>`<tr><th>${l}</th><td>${esc(r.fields[k]?.value||r.fields[k]||'확인 필요')}</td><td>${esc(r.fields[k]?.evidence||'')}</td></tr>`).join('')}</table><h2>2. 적격성 검토</h2><table><tr><th>점검항목</th><th>판정</th><th>검토의견</th></tr>${r.eligibility.map(x=>`<tr><td>${esc(x.item)}</td><td>${esc(x.status)}</td><td>${esc(x.note)}</td></tr>`).join('')}</table><h2>3. 중복성 검토</h2><table><tr><th>유사과제</th><th>유사도</th><th>판정</th><th>의견</th></tr>${r.duplicateReviews.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.similarity)}%</td><td>${esc(x.status)}</td><td>${esc(x.note)}</td></tr>`).join('')}</table><h2>4. 종합결론</h2><p>${esc(r.conclusion)}</p><h2>5. 최종 검토자</h2><p>${esc(r.reviewer.name||'')} / ${esc(r.reviewer.department||'')}</p><p>${esc(r.reviewer.finalComment||'')}</p></html>`;
}
async function docxReport(review) {
  const r=model(review); const rows=[];
  Object.entries(LABELS).forEach(([k,l])=>rows.push(new TableRow({children:[l,r.fields[k]?.value||r.fields[k]||'확인 필요',r.fields[k]?.evidence||''].map(v=>new TableCell({children:[new Paragraph(String(v))]}))})));
  const children=[new Paragraph({text:'ICT R&D 선정평가 사전검토 보고서',heading:HeadingLevel.TITLE}),new Paragraph(`생성일시 ${r.completedAt} · 평가위원 판단 지원용`),new Paragraph({text:'1. 신청과제',heading:HeadingLevel.HEADING_1}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows}),new Paragraph({text:'2. 적격성 검토',heading:HeadingLevel.HEADING_1}),...r.eligibility.map(x=>new Paragraph(`${x.item} | ${x.status} | ${x.note||''}`)),new Paragraph({text:'3. 중복성 검토',heading:HeadingLevel.HEADING_1}),...r.duplicateReviews.map(x=>new Paragraph(`${x.name} (${x.similarity}%) | ${x.status} | ${x.note||''}`)),new Paragraph({text:'4. 종합결론',heading:HeadingLevel.HEADING_1}),new Paragraph(r.conclusion||''),new Paragraph({text:'5. 최종 검토자',heading:HeadingLevel.HEADING_1}),new Paragraph(`${r.reviewer.name||''} / ${r.reviewer.department||''}`),new Paragraph(r.reviewer.finalComment||'')];
  return Packer.toBuffer(new Document({sections:[{children}]}));
}
function pdfReport(review) {
  const r=model(review); return new Promise(resolve=>{const doc=new PDFDocument({margin:48,size:'A4'});const chunks=[];doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));if(PDF_FONT)doc.font(PDF_FONT);doc.fontSize(19).text('ICT R&D 선정평가 사전검토 보고서').moveDown();doc.fontSize(9).fillColor('#667085').text(`생성일시 ${r.completedAt} · 평가위원 판단 지원용`).fillColor('#17233c');doc.fontSize(14).moveDown().text('1. 신청과제');doc.fontSize(10);Object.entries(LABELS).forEach(([k,l])=>doc.text(`${l}: ${r.fields[k]?.value||r.fields[k]||'확인 필요'}`));doc.fontSize(14).moveDown().text('2. 적격성 검토');doc.fontSize(10);r.eligibility.forEach(x=>doc.text(`• ${x.item} [${x.status}] ${x.note||''}`));doc.fontSize(14).moveDown().text('3. 중복성 검토');doc.fontSize(10);r.duplicateReviews.forEach(x=>doc.text(`• ${x.name} (${x.similarity}%) [${x.status}] ${x.note||''}`));doc.fontSize(14).moveDown().text('4. 종합결론');doc.fontSize(10).text(r.conclusion||'');doc.fontSize(14).moveDown().text('5. 최종 검토자');doc.fontSize(10).text(`${r.reviewer.name||''} / ${r.reviewer.department||''}`).text(r.reviewer.finalComment||'');doc.end();});
}
module.exports={htmlReport,docxReport,pdfReport};
